/** @type {import('tailwindcss').Config} */
// Color tokens, spacing, and radii are ported 1:1 from the SplitCheck DESIGN.md
// (Material 3 dynamic color scheme, "Frosted Cyan" seed). Do not rename these
// without updating DESIGN.md — they're meant to stay in lockstep with the
// original Stitch mockups.
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary': '#223336',
        surface: '#131313',
        'surface-dim': '#131313',
        'on-error': '#690005',
        secondary: '#c8c6c8',
        'outline-variant': '#3b4a3d',
        'on-primary-fixed': '#0d1e21',
        'tertiary-fixed': '#e2e2e2',
        'surface-bright': '#393939',
        'on-tertiary-container': '#525454',
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#c8c6c8',
        'on-secondary-fixed-variant': '#474649',
        'on-surface': '#e5e2e1',
        'on-tertiary': '#2f3131',
        'on-tertiary-fixed-variant': '#454747',
        'secondary-container': '#474649',
        'on-background': '#e5e2e1',
        'surface-container-lowest': '#0e0e0e',
        'on-primary-fixed-variant': '#384a4d',
        'on-primary-container': '#45575a',
        'primary-fixed-dim': '#b7cace',
        tertiary: '#e4e4e4',
        'on-surface-variant': '#bacbb9',
        outline: '#859585',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-secondary': '#303032',
        'surface-variant': '#353534',
        'primary-container': '#b9ccd0',
        'on-secondary-fixed': '#1b1b1d',
        'inverse-primary': '#506165',
        'surface-container-high': '#2a2a2a',
        'surface-container': '#201f1f',
        'surface-tint': '#b7cace',
        'tertiary-container': '#c8c8c8',
        'on-secondary-container': '#b6b4b7',
        error: '#ffb4ab',
        'surface-container-low': '#1c1b1b',
        'inverse-on-surface': '#313030',
        'secondary-fixed': '#e4e2e4',
        'inverse-surface': '#e5e2e1',
        background: '#131313',
        'primary-fixed': '#d3e6ea',
        primary: '#d5e8ec',
        'surface-container-highest': '#353534',
      },
      spacing: {
        'stack-sm': '4px',
        gutter: '16px',
        base: '8px',
        'container-padding': '24px',
        'stack-lg': '24px',
        'stack-md': '12px',
      },
    },
  },
  plugins: [],
};
